# Default values for k8s-alert-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: tony24681379/k8s-alert-controller
  tag: lastest
  pullPolicy: IfNotPresent
service:
  name: k8s-alert-controller
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

